sudo : required
services:
  - docker

before_install:
  - docker build -t testing001 -f Dockerfile.dev .

scripts:
  - docker run testing001 npm run test -- --coverage

deploy:
  provider: heroku
  api_key: 2e3d6b2a-2cba-4b7d-90ef-08791ea6ebdf
    secure: 
  app: firstdockerapp001
  on:
    repo:  Ammarulhaq/docker-react